/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import All_Info.Car;
import All_Info.CarInventory;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kunjir
 */
public class AdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form adminPanel
     */
    CarInventory carInv;
    public AdminPanel(CarInventory carInv) {
        initComponents();
        this.carInv = carInv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        txtseats = new javax.swing.JTextField();
        txtcompany = new javax.swing.JTextField();
        adminSavebtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtmodel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtserialno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmfg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtavailability = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelOne = new javax.swing.JTable();
        txtexpdate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        UpdateToView = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel1.setText("                          Welcome to Uber...");

        jLabel2.setText("City:");

        jLabel3.setText("Seats:");

        jLabel4.setText("Company:");

        adminSavebtn.setText("Save");
        adminSavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSavebtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Model:");

        txtmodel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmodelKeyReleased(evt);
            }
        });

        jLabel6.setText("Serial No:");

        jLabel7.setText("Mfg:");

        jLabel8.setText("Availability:");

        jLabel9.setText("ExpDate:");

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        TabelOne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "City", "Seats", "Company", "Model", "Serial No", "Mfg", "Availability", "ExpiryDate"
            }
        ));
        jScrollPane1.setViewportView(TabelOne);

        jLabel10.setText("(Yes/No)");

        UpdateToView.setText("View To Update");
        UpdateToView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateToViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtserialno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtmfg, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminSavebtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtavailability, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(txtexpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addContainerGap(100, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UpdateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ViewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpdateToView)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtserialno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmfg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtavailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtexpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminSavebtn)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpdateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ViewBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateToView)
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = TabelOne.getSelectedRow();

        if(selectedRowIndex < 0){
        JOptionPane.showMessageDialog(this, "Please select a row to delete");
        }

        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        Car car = (Car) model.getValueAt(selectedRowIndex, 0);
        
        carInv.deleteData(car);
        JOptionPane.showMessageDialog(this,"Details Deleted!");
        displayTable();
    }//GEN-LAST:event_DeleteBtnActionPerformed

     public boolean validateData(){
        boolean b = false;
        if(txtcity.getText().isEmpty()){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Valid city");
            txtcity.requestFocus();
        }
         if(txtcompany.getText().isEmpty()){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Valid Company");
            txtcompany.requestFocus();
        }
          if(txtmodel.getText().isEmpty()){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Valid model");
            txtmodel.requestFocus();
            
            
        }
           if(txtavailability.getText().isEmpty()){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter availability");
            txtavailability.requestFocus();
        }
        else 
            b= true;
           
        for(Car car: carInv.getStorage()){
                
               if(car.getModel().equals(txtmodel.getText())){
                   b = false;
                   JOptionPane.showMessageDialog(null, "This model already exist, please enter correct model");
                   break;
               }
           }
            
        return b;
        
     }
           
           
           
            
     
     
     
    
    private void adminSavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSavebtnActionPerformed
        // TODO add your handling code here:
        
        boolean check = validateData();
        
        if(check == true)
        {
        String city = txtcity.getText();
        String seats = txtseats.getText();
        String company = txtcompany.getText();
        String model = txtmodel.getText();
        String serial = txtserialno.getText();
        String mfg = txtmfg.getText();
        String availability = txtavailability.getText();
        Date expdate = txtexpdate.getDate();
        
       
 
        Car car = carInv.addData();
        car.setCity(city);
        car.setCompany(company);
        car.setSeats(Integer.parseInt(seats));
        car.setModel(model);
        car.setSerial(Integer.parseInt(serial));
        car.setAvailability(availability);
        car.setExpdate(expdate);
        car.setMfg(Integer.parseInt(mfg));
        
        txtcity.setText("");
        txtseats.setText("");
        txtcompany.setText("");
        txtmodel.setText("");
        txtserialno.setText("");
        txtavailability.setText("");
//        txtexpdate.setDate("");
        txtmfg.setText("");
        
        JOptionPane.showMessageDialog(this,"Car Details Saved!");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Enter all valid fields");
        }
        
    }//GEN-LAST:event_adminSavebtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = TabelOne.getSelectedRow();

//        if(selectedRowIndex < 0){
//        JOptionPane.showMessageDialog(this, "Please select a row to view");
//        }

        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
       
        
        model.setRowCount(0);
        for(Car carfetch : carInv.getStorage()){
            
            Object[] rows = new Object[8];
            rows[0] = carfetch;
            rows[1] = carfetch.getSeats();
            rows[2] = carfetch.getCompany();
            rows[3] = carfetch.getModel();
            rows[4] = carfetch.getSerial();
            rows[5] = carfetch.getMfg();
            rows[6] = carfetch.getAvailability();
            SimpleDateFormat dateview = new SimpleDateFormat("MM/dd/yyyy");
            rows[7] = dateview.format(carfetch.getExpdate().getTime());
            
            
            model.addRow(rows);
            
            
        }
        
    
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = TabelOne.getSelectedRow();

        if(selectedRowIndex < 0){
        JOptionPane.showMessageDialog(this, "Please select a row to update");
        }

        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
   
        String sno = model.getValueAt(selectedRowIndex, 4).toString();
        int serialNo = Integer.parseInt(sno);

        for(Car car : carInv.getStorage()) {
            if(car.getSerial() == Integer.parseInt(sno)) {
                car.setAvailability(txtavailability.getText());
                car.setCity(txtcity.getText());
                car.setExpdate(txtexpdate.getDate());
                
            }
        }

        displayTable();
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void UpdateToViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateToViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = TabelOne.getSelectedRow();

        if(selectedRowIndex < 0){
        JOptionPane.showMessageDialog(this, "Please select a row to delete");
        }

        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        Car car = (Car) model.getValueAt(selectedRowIndex, 0);
        txtcity.setText(car.getCity());
        txtseats.setText(String.valueOf(car.getSeats()));
        txtcompany.setText(car.getCompany());
        txtmodel.setText(car.getModel());
        txtserialno.setText(String.valueOf(car.getSerial()));
        txtmfg.setText(String.valueOf(car.getMfg()));
        txtavailability.setText(car.getAvailability());
        
        
        JOptionPane.showMessageDialog(this,"Please update details abve");
        
    }//GEN-LAST:event_UpdateToViewActionPerformed

    private void txtmodelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmodelKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtmodelKeyReleased

    public void displayTable(){
         DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        
        
        model.setRowCount(0);
        for(Car carfetch : carInv.getStorage()){
            Object[] rows = new Object[8];
            rows[0] = carfetch.getCity();
            rows[1] = carfetch.getSeats();
            rows[2] = carfetch.getCompany();
            rows[3] = carfetch.getModel();
            rows[4] = carfetch.getSerial();
            rows[5] = carfetch.getMfg();
            rows[6] = carfetch.getAvailability();
            rows[7] = carfetch.getExpdate();
            
            model.addRow(rows);
    }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTable TabelOne;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton UpdateToView;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton adminSavebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtavailability;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcompany;
    private com.toedter.calendar.JDateChooser txtexpdate;
    private javax.swing.JTextField txtmfg;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtseats;
    private javax.swing.JTextField txtserialno;
    // End of variables declaration//GEN-END:variables
}
