/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

 */
package UI;

import All_Info.Car;
import All_Info.CarInventory;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kunjir
 */
public class CatalogPanel extends javax.swing.JPanel {

    /**
     * Creates new form catalogPanel
     */
    CarInventory carInv;
    public CatalogPanel(CarInventory carInv) {
        initComponents();
        this.carInv = carInv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstCar = new javax.swing.JButton();
        txtNoOfCars = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtCarCompany = new javax.swing.JTextField();
        txtSeatsNumber = new javax.swing.JTextField();
        txtCityCatalog = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtManufacturingNumber = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtExpiryCatalog = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelOne = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCarCount = new javax.swing.JTextField();

        txtFirstCar.setText("Find me the first available passenger car");
        txtFirstCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstCarActionPerformed(evt);
            }
        });

        txtNoOfCars.setText("How many cars are currently available");
        txtNoOfCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfCarsActionPerformed(evt);
            }
        });

        jButton3.setText("Cars made by specific company");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Number of Seats");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Serial Number");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Model Number");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Search by Manufacturer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Car search by city");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Expiry Date");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        txtModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumberActionPerformed(evt);
            }
        });

        TabelOne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "City", "Seats", "Company", "Model", "Serial No", "Mfg", "Availability", "ExpiryDate"
            }
        ));
        jScrollPane1.setViewportView(TabelOne);

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel1.setText("        Our Catalog");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFirstCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNoOfCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtModelNumber)
                    .addComponent(txtCarCompany)
                    .addComponent(txtSeatsNumber)
                    .addComponent(txtCarCount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtExpiryCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCityCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtManufacturingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCityCatalog, txtExpiryCatalog, txtManufacturingNumber, txtSerialNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(txtManufacturingNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(txtSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(txtCityCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(txtExpiryCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFirstCar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoOfCars)
                            .addComponent(txtCarCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(txtCarCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(txtSeatsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(79, 79, 79))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCityCatalog, txtExpiryCatalog, txtManufacturingNumber, txtSerialNumber});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      
        int carCompanyType = Integer.parseInt(txtSeatsNumber.getText());
        
        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        model.setRowCount(0);
        
        for(Car car : carInv.getStorage())
        {
            
            if(car.getSeats() == (carCompanyType))
            {
                Object[] row = new Object[8];
                row[0] = car.getCity();
                row[1] = car.getSeats();
                row[2] = car.getCompany();
                row[3] = car.getModel();
                row[4] = car.getSerial();
                row[5] = car.getMfg();
                row[6] = car.getAvailability();
                SimpleDateFormat dateOnly = new SimpleDateFormat("MM/dd/yyyy");
                row[7] = (dateOnly.format(car.getExpdate()));
                
                model.addRow(row);
                
            }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
     
        
        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        model.setRowCount(0);
        
        for(Car car : carInv.getStorage())
        {
            Date dateExpiry = car.getExpdate();
            java.util.Date todayDate = new java.util.Date();

            if(todayDate.after(dateExpiry))
                
            {
                Object[] row = new Object[8];
                row[0] = car.getCity();
                row[1] = car.getSeats();
                row[2] = car.getCompany();
                row[3] = car.getModel();
                row[4] = car.getSerial();
                row[5] = car.getMfg();
                row[6] = car.getAvailability();
                SimpleDateFormat dateOnly = new SimpleDateFormat("MM/dd/yyyy");
                row[7] = (dateOnly.format(car.getExpdate()));
                
                model.addRow(row);
                
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberActionPerformed

    private void txtFirstCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstCarActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        model.setRowCount(0);
        
        for(Car car : carInv.getStorage())
        {
            if(car.getAvailability().equals("yes") || car.getAvailability().equals("Yes"))
            {
                Object[] row = new Object[8];
                row[0] = car.getCity();
                row[1] = car.getSeats();
                row[2] = car.getCompany();
                row[3] = car.getModel();
                row[4] = car.getSerial();
                row[5] = car.getMfg();
                row[6] = car.getAvailability();
                SimpleDateFormat dateOnly = new SimpleDateFormat("MM/dd/yyyy");
                row[7] = (dateOnly.format(car.getExpdate()));
                
                model.addRow(row);
                break;
            }
        }
    }//GEN-LAST:event_txtFirstCarActionPerformed

    private void txtNoOfCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfCarsActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        model.setRowCount(0);
        int count = 0;
        for(Car car : carInv.getStorage())
        {
            if(car.getAvailability().equals("yes") || car.getAvailability().equals("Yes"))
            {
                Object[] row = new Object[8];
                row[0] = car.getCity();
                row[1] = car.getSeats();
                row[2] = car.getCompany();
                row[3] = car.getModel();
                row[4] = car.getSerial();
                row[5] = car.getMfg();
                row[6] = car.getAvailability();
                SimpleDateFormat dateOnly = new SimpleDateFormat("MM/dd/yyyy");
                row[7] = (dateOnly.format(car.getExpdate()));
                
                model.addRow(row);
                count++;
            }
        }
        
        txtCarCount.setText(String.valueOf(count));
    }//GEN-LAST:event_txtNoOfCarsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String carCompanyType = txtCarCompany.getText();
        
        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        model.setRowCount(0);
        int count = 0;
        for(Car car : carInv.getStorage())
        {
            if(car.getCompany().equals(carCompanyType))
            {
                Object[] row = new Object[8];
                row[0] = car.getCity();
                row[1] = car.getSeats();
                row[2] = car.getCompany();
                row[3] = car.getModel();
                row[4] = car.getSerial();
                row[5] = car.getMfg();
                row[6] = car.getAvailability();
                SimpleDateFormat dateOnly = new SimpleDateFormat("MM/dd/yyyy");
                row[7] = (dateOnly.format(car.getExpdate()));
                
                model.addRow(row);
                
            }
        }
        
        txtCarCount.setText(String.valueOf(count));
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        
                
        String carModelType = (txtModelNumber.getText());
        
        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        model.setRowCount(0);
        
        for(Car car : carInv.getStorage())
        {
            JOptionPane.showMessageDialog(this, carModelType + "   "+ car.getModel());
            if(car.getModel().equals(carModelType))
            {
                Object[] row = new Object[8];
                row[0] = car.getCity();
                row[1] = car.getSeats();
                row[2] = car.getCompany();
                row[3] = car.getModel();
                row[4] = car.getSerial();
                row[5] = car.getMfg();
                row[6] = car.getAvailability();
                SimpleDateFormat dateOnly = new SimpleDateFormat("MM/dd/yyyy");
                row[7] = (dateOnly.format(car.getExpdate()));
                
                model.addRow(row);
                
            }
        }
                
                
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    
        int carMfg = Integer.parseInt(txtManufacturingNumber.getText());
        
        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        model.setRowCount(0);
        
        for(Car car : carInv.getStorage())
        {
            
            if(car.getMfg() == (carMfg))
            {
                Object[] row = new Object[8];
                row[0] = car.getCity();
                row[1] = car.getSeats();
                row[2] = car.getCompany();
                row[3] = car.getModel();
                row[4] = car.getSerial();
                row[5] = car.getMfg();
                row[6] = car.getAvailability();
                SimpleDateFormat dateOnly = new SimpleDateFormat("MM/dd/yyyy");
                row[7] = (dateOnly.format(car.getExpdate()));
                
                model.addRow(row);
                
            }
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
       
                        
        String carCityType = (txtCityCatalog.getText());
        
        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        model.setRowCount(0);
        
        for(Car car : carInv.getStorage())
        {
            
            if(car.getCity().equals(carCityType))
            {
                Object[] row = new Object[8];
                row[0] = car.getCity();
                row[1] = car.getSeats();
                row[2] = car.getCompany();
                row[3] = car.getModel();
                row[4] = car.getSerial();
                row[5] = car.getMfg();
                row[6] = car.getAvailability();
                SimpleDateFormat dateOnly = new SimpleDateFormat("MM/dd/yyyy");
                row[7] = (dateOnly.format(car.getExpdate()));
                
                model.addRow(row);
                
            }
        }
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
     
                
                
        int carSn = Integer.parseInt(txtSerialNumber.getText());
        
        DefaultTableModel model = (DefaultTableModel) TabelOne.getModel();
        model.setRowCount(0);
        
        for(Car car : carInv.getStorage())
        {
            
            if(car.getSerial() == (carSn))
            {
                Object[] row = new Object[8];
                row[0] = car.getCity();
                row[1] = car.getSeats();
                row[2] = car.getCompany();
                row[3] = car.getModel();
                row[4] = car.getSerial();
                row[5] = car.getMfg();
                row[6] = car.getAvailability();
                SimpleDateFormat dateOnly = new SimpleDateFormat("MM/dd/yyyy");
                row[7] = (dateOnly.format(car.getExpdate()));
                
                model.addRow(row);
                
            }
        }

                
                
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelOne;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCarCompany;
    private javax.swing.JTextField txtCarCount;
    private javax.swing.JTextField txtCityCatalog;
    private javax.swing.JTextField txtExpiryCatalog;
    private javax.swing.JButton txtFirstCar;
    private javax.swing.JTextField txtManufacturingNumber;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JButton txtNoOfCars;
    private javax.swing.JTextField txtSeatsNumber;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
